// app/reading-goals/goals.styles.ts (또는 적절한 경로)
import { Colors, FontSize, Spacing } from '@/constants/tokens';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgPrimary,
    paddingTop: Spacing.xl,
  },
  pageTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: Colors.textPrimary,
    textAlign: 'center',
    marginBottom: Spacing.xl * 1.2,
    letterSpacing: -0.5,
  },
  screen: {
    flex: 1,
    paddingHorizontal: Spacing.xl,
  },
  scrollContent: {
    paddingBottom: Spacing.xl * 2.5,
  },
  card: {
    backgroundColor: Colors.bgSecondary,
    borderRadius: 24,
    padding: Spacing.xl,
    marginBottom: Spacing.lg,
    boxShadow: '0px 8px 24px rgba(0, 0, 0, 0.02)',
    elevation: 2,
  },
  bookAddBox: {
    height: 110,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    borderStyle: 'dashed',
  },
  plusText: {
    fontSize: FontSize.base,
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#F8F9FA',
  },
  infoLabel: {
    fontSize: FontSize.base,
    color: Colors.textSecondary,
    fontWeight: '500',
  },
  infoValue: {
    flex: 1,
    fontSize: FontSize.base,
    fontWeight: '600',
    color: Colors.textPrimary,
    textAlign: 'right',
  },
  mainButton: {
    backgroundColor: Colors.textPrimary,
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: Spacing.lg,
    boxShadow: '0px 6px 20px rgba(0, 0, 0, 0.08)',
  },
  mainButtonText: {
    color: Colors.bgPrimary,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  backButton: {
    alignItems: 'center',
    marginTop: Spacing.lg,
    paddingVertical: Spacing.sm,
  },
  backButtonText: {
    color: Colors.textTertiary,
    fontSize: FontSize.sm,
    textDecorationLine: 'none',
    opacity: 0.8,
  },
  calendarBox: {
    backgroundColor: Colors.bgSecondary,
    borderRadius: 28,
    padding: Spacing.xl,
    marginTop: Spacing.sm,
    boxShadow: '0px 12px 32px rgba(0, 0, 0, 0.03)',
    elevation: 2,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.xl,
    paddingHorizontal: 4,
  },
  calendarTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  arrowText: {
    fontSize: 20,
    fontWeight: '500',
    color: Colors.textSecondary,
    paddingHorizontal: Spacing.md,
  },
  calendarSelectBox: {
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: '#F3F4F6',
  },
  calendarSelectText: {
    fontSize: FontSize.sm,
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  weekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  weekText: {
    width: `${100 / 7}%`,
    textAlign: 'center',
    color: Colors.textTertiary,
    fontSize: 12,
    fontWeight: '600',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarDay: {
    width: `${100 / 7}%`,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 14,
    marginVertical: 2,
  },
  rangeDay: {
    backgroundColor: '#F4F5F7',
    borderRadius: 0,
  },
  selectedDate: {
    backgroundColor: Colors.textPrimary,
    borderRadius: 14,
  },
  calendarDayText: {
    fontSize: 15,
    fontWeight: '500',
    color: Colors.textPrimary,
  },
  selectedDateText: {
    color: Colors.bgPrimary,
    fontWeight: '700',
  },
  otherMonthText: {
    color: '#E5E7EB',
  },
  selectedDateBox: {
    marginTop: Spacing.lg,
    alignItems: 'center',
  },
  selectedDateTextSmall: {
    fontSize: FontSize.xs,
    color: Colors.textTertiary,
    fontWeight: '500',
  },
  dayRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Spacing.lg,
    marginBottom: Spacing.lg,
  },
  dayButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
  },
  activeDay: {
    backgroundColor: Colors.textPrimary,
    boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.08)',
  },
  dayText: {
    fontSize: 14,
    color: Colors.textSecondary,
    fontWeight: '600',
  },
  activeDayText: {
    color: Colors.bgPrimary,
    fontWeight: '700',
  },
  resultInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginTop: Spacing.md,
  },
  resultLabel: {
    fontSize: FontSize.base,
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  fakeInput: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: '#EFF2FF',
  },
  fakeInputText: {
    fontSize: FontSize.base,
    fontWeight: '700',
    color: '#4F46E5',
  },
  resultBox: {
    alignItems: 'center',
    marginVertical: Spacing.xl * 1.5,
  },
  resultNumber: {
    fontSize: 72,
    fontWeight: '800',
    color: Colors.textPrimary,
    letterSpacing: -2,
  },
  resultText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textTertiary,
    marginTop: 6,
    letterSpacing: -0.1,
  },
  bottomNav: {
    height: 64,
    borderTopWidth: 1,
    borderColor: '#F3F4F6',
    backgroundColor: Colors.bgPrimary,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: 8,
  },
  navItem: {
    fontSize: FontSize.xs,
    color: Colors.textTertiary,
    fontWeight: '500',
  },
  navItemActive: {
    fontSize: FontSize.xs,
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bookModalBox: {
    width: '90%',
    backgroundColor: Colors.bgPrimary,
    borderRadius: 28,
    paddingVertical: Spacing.xl,
    paddingHorizontal: Spacing.xl,
    boxShadow: '0px 20px 48px rgba(0, 0, 0, 0.12)',
    elevation: 5,
  },
  bookModalTitle: {
    fontSize: 19,
    fontWeight: '700',
    marginBottom: Spacing.xl,
    color: Colors.textPrimary,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  searchHeader: {
    width: '100%',
    backgroundColor: '#F8F9FA',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: Spacing.md,
  },
  searchHeaderText: {
    fontSize: 14,
    color: Colors.textTertiary,
    fontWeight: '500',
  },
  searchDropdown: {
    width: '100%',
    backgroundColor: '#F8F9FA',
    borderRadius: 14,
    padding: Spacing.md,
    maxHeight: 220,
    marginBottom: Spacing.md,
  },
  searchInput: {
    fontSize: 15,
    color: Colors.textPrimary,
    borderBottomWidth: 1.5,
    borderBottomColor: '#EFEFEF',
    paddingBottom: 10,
    marginBottom: Spacing.sm,
  },
  loadingText: {
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: 'center',
    paddingVertical: Spacing.sm,
  },
  emptyText: {
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: 'center',
    paddingVertical: Spacing.sm,
  },
  searchResult: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F8F9FA',
  },
  searchResultTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: Colors.textPrimary,
    letterSpacing: -0.2,
  },
  searchResultAuthor: {
    fontSize: 12,
    color: Colors.textTertiary,
    marginTop: 3,
  },
  manualInputBox: {
    width: '100%',
    gap: Spacing.md,
  },
  manualInput: {
    backgroundColor: '#F8F9FA',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 15,
    color: Colors.textPrimary,
  },
  modalButtonRow: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginTop: Spacing.xl,
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: '#F3F4F6',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
  },
  modalConfirmButton: {
    flex: 1,
    backgroundColor: Colors.textPrimary,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
  },
  modalCancelText: {
    color: Colors.textSecondary,
    fontWeight: '600',
    fontSize: 15,
  },
  modalConfirmText: {
    color: Colors.bgPrimary,
    fontWeight: '700',
    fontSize: 15,
  },
});