import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  title: {
    textAlign: "center",
    fontSize: 22,
    fontWeight: "700",
    color: "#333",
    marginTop: 8,
    marginBottom: 12,
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 16,
    marginBottom: 12,
  },
  activeTabButton: {
    flex: 1,
    backgroundColor: "#E2ECE5",
    paddingVertical: 14,
    alignItems: "center",
    borderRadius: 14,
    marginRight: 6,
    borderWidth: 1,
    borderColor: "#C2E2CC",
  },
  activeTabText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2E6943",
  },
  tabButton: {
    flex: 1,
    backgroundColor: "#fff",
    paddingVertical: 14,
    alignItems: "center",
    borderRadius: 14,
    marginLeft: 6,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  tabText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#777",
  },
  addButton: {
    backgroundColor: "#fff",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  addButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#333",
  },
  timelineContainer: {
    paddingHorizontal: 16,
    paddingBottom: 100,
    paddingTop: 10,
  },
  timelineWrapper: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 16,
    position: "relative",
  },
  // 중간 타래들의 세로선 (다음 타래로 쭉 이어짐)
  itemLine: {
    width: 2,
    backgroundColor: "#C2DBC2",
    position: "absolute",
    left: 20,
    top: 0,
    bottom: -16,
  },
  // 제일 마지막 타래의 세로선 (동그라미 중앙에서 딱 멈춤)
  lastItemLine: {
    width: 2,
    backgroundColor: "#C2DBC2",
    position: "absolute",
    left: 20,
    top: 0,
    height: 27,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#C2DBC2",
    position: "absolute",
    left: 16,
    top: 22,
    zIndex: 2,
  },
  // 모든 타래 공통으로 깔끔한 일직선 가로 연결선 사용
  connectorLine: {
    width: 24,
    height: 2,
    backgroundColor: "#C2DBC2",
    marginTop: 26,
    marginLeft: 18,
  },
  emptyText: {
    textAlign: "center",
    color: "#777",
    marginTop: 30,
    marginBottom: 30,
  },
  card: {
    flex: 1,
    marginRight: 16,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: "#EAEAEA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  summaryCard: {
    backgroundColor: "#E8F3EC",
    borderWidth: 1,
    borderColor: "#C2E2CC",
  },
  cardTop: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  page: {
    fontSize: 12,
    color: "#777",
  },
  date: {
    fontSize: 12,
    color: "#999",
  },
  summaryLabel: {
    fontSize: 13,
    color: "#2E6943",
    fontWeight: "700",
  },
  content: {
    fontSize: 14,
    color: "#333",
    lineHeight: 22,
  },
  summaryContent: {
    fontSize: 14,
    color: "#2C3E31",
    lineHeight: 22,
    fontWeight: "500",
  },
  aiButton: {
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: "#4A3B32",
  },
  aiButtonFixed: {
    position: "absolute",
    bottom: 20,
    left: 16,
    right: 16,
    backgroundColor: "#E2D7F0",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#C5B3E0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  aiButtonText: {
    fontSize: 15,
    color: "#6A5A8C",
    fontWeight: "700",
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalBox: {
    width: "86%",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 22,
  },
  modalTitle: {
    textAlign: "center",
    marginBottom: 16,
    fontWeight: "700",
    fontSize: 18,
    color: "#333",
  },
  pageInput: {
    width: 70,
    backgroundColor: "#F8F7F5",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  pgText: {
    marginLeft: 78,
    marginTop: -28,
    marginBottom: 16,
    color: "#555",
  },
  contentInput: {
    height: 150,
    backgroundColor: "#F8F7F5",
    borderRadius: 12,
    padding: 14,
    textAlignVertical: "top",
    marginBottom: 18,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  modalButton: {
    flex: 1,
    backgroundColor: "#F0EFED",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  cardButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 14,
  },
  smallButton: {
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#F0EFED",
  },
  smallButtonText: {
    fontSize: 12,
    color: "#333",
  },
});