import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F0EFED",
  },
  title: {
    textAlign: "center",
    fontSize: 22,
    fontWeight: "700",
    color: "#333",
    marginTop: 8,
    marginBottom: 18,
  },
  addButton: {
    backgroundColor: "#fff",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  addButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#333",
  },
  threadArea: {
    paddingHorizontal: 16,
    paddingBottom: 90,
  },
  emptyText: {
    textAlign: "center",
    color: "#777",
    marginTop: 30,
    marginBottom: 30,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  summaryCard: {
    backgroundColor: "#E8F3EC",
    borderWidth: 1,
    borderColor: "#C2E2CC",
  },
  cardTop: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  page: {
    fontSize: 12,
    color: "#777",
  },
  date: {
    fontSize: 12,
    color: "#999",
  },
  summaryLabel: {
    fontSize: 13,
    color: "#2E6943",
    fontWeight: "700",
  },
  content: {
    fontSize: 14,
    color: "#333",
    lineHeight: 22,
  },
  summaryContent: {
    fontSize: 14,
    color: "#2C3E31",
    lineHeight: 22,
    fontWeight: "500",
  },
  aiButton: {
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    marginHorizontal: 48,
    marginTop: 4,
    backgroundColor: "#4A3B32",
  },
  aiButtonText: {
    fontSize: 13,
    color: "#fff",
    fontWeight: "700",
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalBox: {
    width: "86%",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 22,
  },
  modalTitle: {
    textAlign: "center",
    marginBottom: 16,
    fontWeight: "700",
    fontSize: 18,
    color: "#333",
  },
  pageInput: {
    width: 70,
    backgroundColor: "#F8F7F5",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  pgText: {
    marginLeft: 78,
    marginTop: -28,
    marginBottom: 16,
    color: "#555",
  },
  contentInput: {
    height: 150,
    backgroundColor: "#F8F7F5",
    borderRadius: 12,
    padding: 14,
    textAlignVertical: "top",
    marginBottom: 18,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  modalButton: {
    flex: 1,
    backgroundColor: "#F0EFED",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  cardButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 14,
  },
  smallButton: {
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#F0EFED",
  },
  smallButtonText: {
    fontSize: 12,
    color: "#333",
  },
});